# SLAM Toolbox params
slam_toolbox:
  ros__parameters:
    use_sim_time: false
    map_file_name: /tmp/slam_map
    mode: mapping
    resolution: 0.05
    max_laser_range: 8.0
    minimum_time_interval: 0.5
    transform_publish_period: 0.05
    map_update_interval: 5.0
    publish_period: 1.0
